# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Data Policy
subtitle: Collection

description: >
  OpenDataPolicies.org provides the open-data policies for cities and states
  all over the United States on one website.

legalnotice: >
  All user-contributed content is owned by its authors. The laws are owned by the
  people and, consequently, are not governed by copyright—so do whatever you want
  with them. This website does not constitute legal advice. While every effort is made to keep all information
  up-to-date and accurate, no guarantee is made as to its accuracy. Our <a href=" http://sunlightfoundation.com/legal/privacy/">privacy policy</a> details how personally identfiable information that is collected on our websites is handled. Read our <a href=" http://sunlightfoundation.com/legal/terms/">terms of service.</a>

credits: >
  This work by the Sunlight Foundation, unless otherwise noted, is licensed under a <a href="https://creativecommons.org/licenses/by/3.0/us/">Creative Commons Attribution 3.0 United States License</a>.
  <br>Design by <a href="http://www.meticulous.com">Meticulous</a>.

baseurl: ""
permalink: ":title/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - templates

# Jekyll collections
collections:
  documents:
    output: true
    permalink: /doc/:path/
  states:
    output: true
    permalink: /state/:path/
  places:
    output: false
    permalink: /place/:path/
  guidelines:
    output: true
    permalink: /guidelines/:path/

# Default settings
defaults:
  - scope:
      path: ""
      type: documents
    values:
      layout: policy
      comments: true
      sunlight: nil
  - scope:
      path: ""
      type: states
    values:
      layout: state
  - scope:
      path: ""
      type: places
    values:
      layout: default
      type: local
      no_text: false
      wwc: nil
  - scope:
      path: ""
      type: guidelines
    values:
      layout: guideline

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# APIs

# Google custom search will generate some code with a cx variable, put it's value here.
google_search_code: "016815729111879890803:suyx7g6exsw"

# Google services
google_analytics: UA-48789618-3

# Disqus post comments
disqus_shortname: opendatapolicies
